AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Slack-Team-IoT-Reaction-Bot

Resources:
  SlackChannelSubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/slack_channel_subscribe/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 10
      Events:
        Message:
          Type: Api
          Properties:
            Path: /message
            Method: post

  SlackChannelSubscribeFunctionLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: !Sub /aws/lambda/${SlackChannelSubscribeFunction}

Outputs:
  SlackMessageApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/message/"
